### ISSUE TITLE
tf.placeholder() is not compatible with eager execution

### ISSUE THREAD

**Issue by Kvit** [ltgoslo/simple_elmo_training#4]
Looks like it does not with TF2 even if I try to disable eager execution feature
```
import tensorflow as tf

tf.config.run_functions_eagerly(False)
tf.executing_eagerly()
```

**Comment by Kvit** [comment]
I have managed to start training on Colab after downgrading Tensorflow to Version 1.5
`! pip install tensorflow==1.15.0`

**Comment by akutuzov** [comment]
Yes, this code is for TensorFlow 1, as specified in the `requirements.txt` file.
We plan to update it to TF2, though.
