### ISSUE TITLE
Script does not create checkpoint folder

### ISSUE THREAD

**Issue by Kvit** [ltgoslo/simple_elmo_training#5]
When starting training the script does not create checkpoint folder, I had to create empty folder manually to avoid error.

**Comment by akutuzov** [comment]
The idea is that most probably you already have a dedicated directory for the model you are training (and this directory contains at least the vocabulary file).

**Comment by Kvit** [comment]
In my case, I create several models from the same source data and vocab.  so remembering to create a new checkpoint directory manually each time before execution is not very convenient (or obvious from documentation), would be nice if the script saved vocab to the new model dir if such is available.

**Comment by akutuzov** [comment]
Makes sense, will work on that.
